keycloakx:
  # This is an example configuration, for production grade configuration see the Keycloak documentation.
  # See https://www.keycloak.org/server/configuration
  # See https://www.keycloak.org/server/all-config
  command:
    - "/opt/keycloak/bin/kc-with-setup.sh"
    - "--verbose"
    - "start"
    - "--http-enabled=true"
    - "--http-port=8080"
    - "--hostname-strict=false"
    - "--spi-events-listener-jboss-logging-success-level=info"
    - "--spi-events-listener-jboss-logging-error-level=warn"

  image:
    # The custom image repository
    repository: ${docker.registry}${docker.image.name}
    # Overrides the Keycloak image tag whose default is the chart appVersion
    tag: ${project.version}

  http:
    relativePath: "/"

  extraEnv: |
    - name: KEYCLOAK_ADMIN
      valueFrom:
        secretKeyRef:
          name: {{ include "keycloak.fullname" . }}-admin-creds
          key: user
    - name: KEYCLOAK_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: {{ include "keycloak.fullname" . }}-admin-creds
          key: password
    - name: JAVA_OPTS_APPEND
      value: >-
        -Djava.awt.headless=true
        -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless

  dbchecker:
    enabled: true

  database:
    vendor: postgres
    hostname: postgres-postgresql
    port: 5432
    username: keycloak
    password: keycloak
    database: keycloak

  secrets:
    admin-creds:
      annotations:
        my-test-annotation: Test secret for {{ include "keycloak.fullname" . }}
      stringData:
        user: admin
        password: secret

  securityContext:
    # See https://github.com/keycloak/keycloak/issues/11286
    # readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

  serviceAccount:
    automountServiceAccountToken: "false"
    imagePullSecrets:
      - name: keycloak-custom
