name: 'Setup Java'
description: 'Sets up Java'
inputs:
  java-version:
    description: 'Java version'
    required: true
    default: '21'
  settings-path:
    description: 'Maven related setting to point to the directory where the settings.xml file will be written. Default is ~/.m2.'
    required: false
    default: '~/.m2'
  cache-maven:
    description: 'Enable Maven dependency caching'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java-version }}
        settings-path: ${{ inputs.settings-path }}
        overwrite-settings: false

    - name: Cache Maven dependencies
      if: ${{ inputs.cache-maven == 'true' }}
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-