# Mailpit: https://github.com/axllent/mailpit

services:
  mailpit:
    image: axllent/mailpit:v1.29
    restart: unless-stopped
    ports:
      # SMTP port
      - "1025:1025"
      # Web port
      - "8025:8025"
