name: Build Pipeline

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: generate settings.xml
        uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: |
            [
              {
                "id": "kcc-maven-staging",
                "username": "${KCC_CI_USERNAME}",
                "password": "${KCC_CI_PASSWORD}"
              }
            ]

      - name: Replace "SNAPSHOT" within POM version with date, build number and commit hash
        run: |
          snapshot_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          major_minor_patch=$(echo "${snapshot_version}" | sed "s/SNAPSHOT//g")
          date=$(date -u +%Y%m%d%H%M)
          release_candidate_version=${major_minor_patch}${date}-${{github.run_number}}-${GITHUB_SHA::7}
          echo "RELEASE_CANDIDATE_VERSION=$release_candidate_version" >> $GITHUB_ENV
          mvn versions:set -DnewVersion=${release_candidate_version}

      - name: Run flatten-maven-plugin for extension
        run: mvn process-resources org.codehaus.mojo:flatten-maven-plugin:1.7.0:flatten -Dflatten.dependency.mode=all -Dflatten.mode=bom -Dee.maven.groupId=org.wildfly --file extensions/keycloak-sms-authenticator/pom.xml

      - name: Build with Maven
        run: mvn -B install -Dbuild.number=${{github.run_number}} -Dbuild.revision=${GITHUB_SHA} --file pom.xml

      - name: Deploy with Maven
        run: mvn -B deploy -Dbuild.number=${{github.run_number}} -Dbuild.revision=${GITHUB_SHA} --file extensions/keycloak-sms-authenticator/.flattened-pom.xml
        env:
          KCC_CI_USERNAME: ${{secrets.KCC_CI_USERNAME}}
          KCC_CI_PASSWORD: ${{secrets.KCC_CI_PASSWORD}}

      - name: Check for uncommited code
        run: ./.github/scripts/check_clean_working_directory.sh

      - name: Build summary
        run: |
          echo "### Build successful! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "- Version \`$RELEASE_CANDIDATE_VERSION\`" >> $GITHUB_STEP_SUMMARY
