name: Release
run-name: 'Release of version ${{ inputs.version }} triggered by ${{ github.actor }} on ${{ github.ref }}'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to release'
        type: string
        required: true